In [1]:
#PDP report txt to csv script 
#Author:James Kwok
#Date:11/9/2023
import pandas as pd


data = pd.read_fwf(
    r"C:\Users\jamesk\Downloads\ED16615P2_16615_NCA_NCT_NGN_NUI_20240915103833.txt", delimiter =';',header = None)
data.to_excel(r'C:\Users\jamesk\Downloads\sample EGWP PDP report.xlsx',index = False,header =False)

In [2]:
import openpyxl 
from openpyxl import load_workbook
wb=openpyxl.load_workbook(r'C:\Users\jamesk\Downloads\sample EGWP PDP report.xlsx')
wb2=openpyxl.load_workbook(r'C:\Users\jamesk\Downloads\EGWP Weekly PDP Report Template.xlsx')
wb3=openpyxl.load_workbook(r'L:\Death Master\PGold DOD Reports\Deceased Members 09-16-2024.xlsx')
sheet= wb['Sheet1']
sheet2 = wb2['Details']
sheet4=wb2['PGOLD Death']
sheet3= wb3['Deceased Members']

In [3]:
rows=20000
columns = 66 

listab=[]
for i in range(1,rows+1):
    listab.append([])

    #copy sheet 
for r in range(1,rows+1):
    for c in range (1,columns+1):
        e=sheet.cell(row=r,column=c)
        listab[r-1].append(e.value)
    #paste sheet to sheet2 details
for r in range(1,rows+1):
    for c in range(1,columns+1):
        j=sheet2.cell(row=r+1,column=c)
        j.value=listab[r-1][c-1]

In [4]:
rows=2000
columns = 6 

listab=[]
for i in range(1,rows+1):
    listab.append([])
    #copy deceased memebers from dod
for r in range(1,rows+1):
    for c in range (1,columns+1):
        e=sheet3.cell(row=r,column=c)
        listab[r-1].append(e.value)
    #paste to pgold death sheet4 
for r in range(1,rows+1):
    for c in range(1,columns+1):
        j=sheet4.cell(row=r,column=c)
        j.value=listab[r-1][c-1]
sheet4.delete_rows(1)
sheet4.delete_rows(1)
sheet4.delete_cols(1)
Link=r'L:\ESI\PDP Weekly Reports\2024 Reports\2024 09 16 EGWP PDP report.xlsx'
wb2.save(Link)

In [5]:
import pandas as pd
PDP1 = pd.read_excel(r'L:\ESI\PDP Weekly Reports\2024 Reports\2024 09 10 EGWP PDP report.xlsx', sheet_name='Details')

In [6]:
import pandas as pd
PDP2 = pd.read_excel(Link, sheet_name='Details')

In [7]:
MAX_1 = PDP1.loc[:,'Op. Dte'].max()
print(MAX_1)

20240907

In [8]:
PDP2.loc[:,'Op. Dte'].max()

20240914

In [9]:
#Medicare A 
A=PDP2.loc[(PDP2['Op. Dte'] >MAX_1) & (PDP2['Status Code'] == 8) & (PDP2['TRR'] =='079') ]
A

Empty DataFrame
Columns: [HIC, LT NME, FT NME, MI, Sex, DOB, PBP #, CMS Contract #, Dis. Reason, Eff. DTE, Creditable Cov Flag, # of Uncovered Months, Filler, Pov Level, Grp. #, SSN, TRR, TRR Txt, Dis Dte, Contract ID, carrier, Mem #, Status Code, New Sub. , Change IND, Op. Dte, Reason Code, Current Group Effective Date, Filler1, Filler2, Date of Death, LICS_Copay_Cat1, LICS_Subsidy_Pct_1, LICS_Eff_Dte_1, LICS_End_dte_1, LICS_Copay_Cat_2, LICS_Subsidy_Pct_2, LICS_Eff_Dte_2, LICS_End_dte_2, LICS_Copay_Cat_3, LICS_Subsidy_Pct_3, LICS_Eff_Dte_3, LICS_End_dte_3, LICS_Copay_Cat_4, LICS_Subsidy_Pct_4, LICS_Eff_Dte_4, LICS_End_dte_4, LICS_Copay_Cat_5, LICS_Subsidy_Pct_5, LICS_Eff_Dte_5, LICS_End_dte_5, LEP_Eff_Dte_1, LEP_End_dte_1, LEP_Amt_1, LEP_Eff_Dte_2, LEP_End_dte_2, LEP_Amt_2, LEP_Eff_Dte_3, LEP_End_dte_3, LEP_Amt_3, Subscriber_Nbr, Previous HICN, Multiple EGWP Indicator, Participant ID 4, Dual Coverage Ind, Last Reject Desc]
Index: []

[0 rows x 66 columns]

In [10]:
#Medicare B
B=PDP2.loc[(PDP2['Op. Dte'] >MAX_1) & (PDP2['Status Code'] == 8) & (PDP2['TRR'] == '081') ]
B

,HIC,LT NME,FT NME,MI,Sex,DOB,PBP #,CMS Contract #,Dis. Reason,Eff. DTE,...,LEP_Amt_2,LEP_Eff_Dte_3,LEP_End_dte_3,LEP_Amt_3,Subscriber_Nbr,Previous HICN,Multiple EGWP Indicator,Participant ID 4,Dual Coverage Ind,Last Reject Desc
1778,2CU0RY4PQ36,RICHARDSON,JANICE,I,2,19500116,801,S5660,,20150101,...,,,,,344421367,,,,,
3501,3DK6J94UT61,THURMAN,LILLIE,K,2,19550306,801,S5660,,20200301,...,,,,,336484681,,,,,
8451,6C85F93EN57,GOODMAN,RUTH,B,2,19330630,801,S5660,,20120101,...,,,,,179366431793,,,,,

In [11]:
#Disenrollment 
O=PDP2.loc[(PDP2['Op. Dte'] >MAX_1) & (PDP2['Status Code'] == 16) & (PDP2['Date of Death'] =='        ') ]
O

,HIC,LT NME,FT NME,MI,Sex,DOB,PBP #,CMS Contract #,Dis. Reason,Eff. DTE,...,LEP_Amt_2,LEP_Eff_Dte_3,LEP_End_dte_3,LEP_Amt_3,Subscriber_Nbr,Previous HICN,Multiple EGWP Indicator,Participant ID 4,Dual Coverage Ind,Last Reject Desc
293,1EW7CV6FQ50,HAEGELE,JANET,M,2,19500523,801,S5660,,20150501,...,,,,,349440005,,,,,
2531,2NY0YF7YA28,LYLES,RUBY,P,2,19380725,801,S5660,,20120101,...,,,,,371402385,,,,,
5545,4H72CT6QX14,HIDALGO,EVA,,2,19570522,801,S5660,,20220501,...,,,,,334567747,,,,,
6876,5EJ0NA7MC37,HAZLETT,MARY ANN,,2,19410607,801,S5660,,20120701,...,,,,,326347470,,,,,
6955,5FG5UG9XR77,BIRT-BUTLER,LETTIE,J,2,19501128,801,S5660,,20151101,...,,,,,336442873,,,,,
7775,5R47DW4XK41,HELM,CYNTHIA,J,2,19531004,801,S5660,M09,20181001,...,,,,,407748713,,,,,
12218,8JK8JU7YV33,JONES,ELSIE,H,2,19331114,801,S5660,,20120101,...,,,,,352265731,,,,,
13076,8WY2C92DT01,GUMBINER,GAIL,S,2,19480414,801,S5660,,20130401,...,,,,,342427411,,,,,
14767,9WV4XA9GX63,SHERROD,LUCILE,C,2,19430527,801,S5660,,20120101,...,,,,,424580428,,,,,
14931,9YY3RE9GX16,CALDERO,OLGA,I,2,19520105,801,S5660,,20170101,...,,,,,583548534,,,,,

In [12]:
D=PDP2.loc[(PDP2['Op. Dte'] >MAX_1) & (PDP2['Status Code'] == 16) & (PDP2['Date of Death'] !='        ') ]
D

,HIC,LT NME,FT NME,MI,Sex,DOB,PBP #,CMS Contract #,Dis. Reason,Eff. DTE,...,LEP_Amt_2,LEP_Eff_Dte_3,LEP_End_dte_3,LEP_Amt_3,Subscriber_Nbr,Previous HICN,Multiple EGWP Indicator,Participant ID 4,Dual Coverage Ind,Last Reject Desc
1184,1R35KY8UU67,MOFFATT,KENNETH,E,1,19420121,801,S5660,,20120101,...,,,,,322343376,,,,,
1597,1YP3KC7WY79,SMITH,CHERYL,E,2,19460211,801,S5660,,20120101,...,,,,,331366852,,,,,
2159,2HA3V42TW06,RAFFEL,BARRY,L,1,19420421,801,S5660,,20120101,...,,,,,359340260,,,,,
2201,2HU1UV6AG00,MHOON,JUANITA,P,2,19270730,801,S5660,,20180101,...,,,,,414342103,,,,,
2338,2KF8TA1JN43,CHAPMAN,ROBERTA,A,2,19380520,801,S5660,,20120101,...,,,,,327304133,,,,,
2595,2PP2PV6FE83,ARCHIBALD,BEVERLY,P,2,19290210,801,S5660,,20120101,...,,,,,338229138,,,,,
2870,2TQ3X21MR13,PAUL,ROBERT,E,1,19440925,801,S5660,,20120101,...,,,,,326369336,,,,,
3647,3FA7HM7AA69,CONNOLLY,ANGELA,P,2,19300913,801,S5660,,20120101,...,,,,,346243692,,,,,
3705,3F08F14DY10,MURPHY,DOROTHY,A,2,19271130,801,S5660,,20120101,...,,,,,325208797,,,,,
4115,3M82UK6XK25,BIENIARZ,ALICE,L,2,19301205,801,S5660,,20130101,...,,,,,354245278,,,,,
4501,3TV8R32JH41,THOMPSON,GEORGE,R,1,19300328,801,S5660,,20170201,...,,,,,359220315,,,,,
4627,3VD4GC9AV67,MCCLENDON,SYLVIA,S,2,19340402,801,S5660,,20120101,...,,,,,329264238,,,,,
5136,4DH0K02NP06,WILLIAMS,GERTRUDE,L,2,19480725,801,S5660,,20170201,...,,,,,349408062,,,,,
8719,6GM3UU2RH03,ONGMAN,AUDREY,M,2,19270328,801,S5660,,20120101,...,,,,,345206795,,,,,
9360,6Q95WE0EV54,CASTILLON,MANUEL,H,1,19560521,801,S5660,,20210801,...,,,,,360744945,,,,,
9571,6UP3R40DX18,WOODDELL,PHYLLIS,E,2,19390522,801,S5660,,20160101,...,,,,,166306580,,,,,
9997,7AU2AN3CN14,SIMMONS,DONOVAN,,1,19460623,801,S5660,,20120101,...,,,,,350381241,,,,,
10911,7QD7T13KX49,BELT,GLORIA,,2,19290706,801,S5660,,20120101,...,,,,,357226131,,,,,
11045,7R45W99KK71,PAHLKE,BARBARA,J,2,19500228,801,S5660,,20150201,...,,,,,340427312,,,,,
11274,7VR9R79CJ58,CAMP,BARRY,C,1,19420302,801,S5660,,20120101,...,,,,,254641981,,,,,
12873,8UC6YT8HD62,TURMAN JR,ISAAC,,1,19370328,801,S5660,,20120101,...,,,,,429701922,,,,,
13569,9E15Y62AW87,MERSHIMER,JOY,C,2,19380607,801,S5660,,20120101,...,,,,,369382676,,,,,
14857,9X48D78QY42,BARROW,JOHNNIE,L,1,19320217,801,S5660,,20120101,...,,,,,432580722,,,,,

In [13]:
import openpyxl 
from openpyxl import load_workbook

wb2=openpyxl.load_workbook(r'C:\Users\JamesK\Downloads\test.xlsx')

wb2['Sheet1'].delete_rows(1, sheet.max_row)

sheet2 = wb2['Sheet1']



wb2.save(r'C:\Users\JamesK\Downloads\test.xlsx')

In [14]:
Medicare_A = pd.read_excel(r'C:\Users\JamesK\Downloads\test.xlsx', sheet_name='Sheet1')

filtered_data =PDP2.loc[(PDP2['Op. Dte'] >MAX_1) & (PDP2['Status Code'] == 8) & (PDP2['TRR'] =='079') ]


combined_data=pd.concat([Medicare_A,filtered_data])
combined_data.to_excel(r'C:\Users\JamesK\Downloads\test.xlsx', sheet_name='Sheet1', index=False)

In [15]:
import openpyxl 
from openpyxl import load_workbook
wb=openpyxl.load_workbook(Link)
wb2=openpyxl.load_workbook(r'C:\Users\JamesK\Downloads\test.xlsx')


sheet= wb['A']
sheet2 = wb2['Sheet1']



rows=50
columns = 66 

listab=[]
for i in range(1,rows+1):
    listab.append([])
    #copy a
for r in range(1,rows+1):
    for c in range (1,columns+1):
        e=sheet2.cell(row=r,column=c)
        listab[r-1].append(e.value)
    #paste to a
for r in range(1,rows+1):
    for c in range(1,columns+1):
        j=sheet.cell(row=r,column=c)
        j.value=listab[r-1][c-1]


wb.save(Link)
wb2['Sheet1'].delete_rows(1, sheet.max_row)

In [16]:
Medicare_B = pd.read_excel(r'C:\Users\JamesK\Downloads\test.xlsx', sheet_name='Sheet1')

filtered_data =PDP2.loc[(PDP2['Op. Dte'] >MAX_1) & (PDP2['Status Code'] == 8) & (PDP2['TRR'] == '081') ]


combined_data=pd.concat([Medicare_A,filtered_data])
combined_data.to_excel(r'C:\Users\JamesK\Downloads\test.xlsx', sheet_name='Sheet1', index=False)

In [17]:
import openpyxl 
from openpyxl import load_workbook
wb=openpyxl.load_workbook(Link)
wb2=openpyxl.load_workbook(r'C:\Users\JamesK\Downloads\test.xlsx')

sheet= wb['B']
sheet2 = wb2['Sheet1']

rows=50
columns = 66 

listab=[]
for i in range(1,rows+1):
    listab.append([])
    #copy b
for r in range(1,rows+1):
    for c in range (1,columns+1):
        e=sheet2.cell(row=r,column=c)
        listab[r-1].append(e.value)
    #paste b 
for r in range(1,rows+1):
    for c in range(1,columns+1):
        j=sheet.cell(row=r,column=c)
        j.value=listab[r-1][c-1]


wb.save(Link)
wb2['Sheet1'].delete_rows(1, sheet.max_row)

In [18]:
Medicare_O = pd.read_excel(r'C:\Users\JamesK\Downloads\test.xlsx', sheet_name='Sheet1')

filtered_data =PDP2.loc[(PDP2['Op. Dte'] >MAX_1) & (PDP2['Status Code'] == 16) & (PDP2['Date of Death'] =='        ') ]


combined_data=pd.concat([Medicare_A,filtered_data])
combined_data.to_excel(r'C:\Users\JamesK\Downloads\test.xlsx', sheet_name='Sheet1', index=False)

In [19]:
import openpyxl 
from openpyxl import load_workbook
wb=openpyxl.load_workbook(Link)
wb2=openpyxl.load_workbook(r'C:\Users\JamesK\Downloads\test.xlsx')


sheet= wb['O']
sheet2 = wb2['Sheet1']

rows=50
columns = 66 

listab=[]
for i in range(1,rows+1):
    listab.append([])
    #copy o
for r in range(1,rows+1):
    for c in range (1,columns+1):
        e=sheet2.cell(row=r,column=c)
        listab[r-1].append(e.value)
    #paste o
for r in range(1,rows+1):
    for c in range(1,columns+1):
        j=sheet.cell(row=r,column=c)
        j.value=listab[r-1][c-1]


wb.save(Link)
wb2['Sheet1'].delete_rows(1, sheet.max_row)

In [20]:
Medicare_D = pd.read_excel(r'C:\Users\JamesK\Downloads\test.xlsx', sheet_name='Sheet1')

filtered_data =PDP2.loc[(PDP2['Op. Dte'] >MAX_1) & (PDP2['Status Code'] == 16) & (PDP2['Date of Death'] !='        ') ]


combined_data=pd.concat([Medicare_A,filtered_data])
combined_data.to_excel(r'C:\Users\JamesK\Downloads\test.xlsx', sheet_name='Sheet1', index=False)

In [21]:
import openpyxl 
from openpyxl import load_workbook
wb=openpyxl.load_workbook(Link)
wb2=openpyxl.load_workbook(r'C:\Users\JamesK\Downloads\test.xlsx')


sheet= wb['PDP Death']
sheet2 = wb2['Sheet1']

rows=50
columns = 66 

listab=[]
for i in range(1,rows+1):
    listab.append([])
    #copy d
for r in range(1,rows+1):
    for c in range (1,columns+1):
        e=sheet2.cell(row=r,column=c)
        listab[r-1].append(e.value)
    #paste d
for r in range(1,rows+1):
    for c in range(1,columns+1):
        j=sheet.cell(row=r,column=c)
        j.value=listab[r-1][c-1]
        
        
sheet.delete_cols(32,66)
sheet.delete_cols(1,15)
sheet['Q2'] ="=VLOOKUP(A2,'PGOLD Death'!$A$2:$D$1000,4,FALSE)"

wb.save(Link)
wb2['Sheet1'].delete_rows(1, sheet.max_row)

In [22]:
# import openpyxl 
# from openpyxl import load_workbook

# wb2=openpyxl.load_workbook(r'C:\Users\JamesK\Downloads\test.xlsx')

# wb2['Sheet1'].delete_rows(1, sheet.max_row)

# sheet2 = wb2['Sheet1']



# wb2.save(r'C:\Users\JamesK\Downloads\test.xlsx')

In [23]:
# import openpyxl 
# from openpyxl import load_workbook
# wb=openpyxl.load_workbook(r'L:\ESI\PDP Weekly Reports\2023 Reports\2023 11 07 EGWP PDP report.xlsx')



# sheet= wb['PDP Death']

# sheet.delete_cols(32,66)
# sheet.delete_cols(1,15)

# wb.save(r'L:\ESI\PDP Weekly Reports\2023 Reports\2023 11 07 EGWP PDP report.xlsx')