In [1]:
#PDP report txt to csv script 
#Author:James Kwok
#Date:11/9/2023
import pandas as pd


data = pd.read_fwf(
    r"C:\Users\kwokj\Downloads\ED16615P2_16615_NCA_NCT_NGN_NUI_20241013091139.txt", delimiter =';',header = None)
data.to_excel(r'C:\Users\kwokj\Downloads\sample EGWP PDP report.xlsx',index = False,header =False)

In [2]:
import openpyxl 
from openpyxl import load_workbook
wb=openpyxl.load_workbook(r'C:\Users\kwokj\Downloads\sample EGWP PDP report.xlsx')
wb2=openpyxl.load_workbook(r'C:\Users\kwokj\Downloads\EGWP Weekly PDP Report Template.xlsx')
wb3=openpyxl.load_workbook(r'L:\Death Master\PGold DOD Reports\Deceased Members 10-14-2024.xlsx')
sheet= wb['Sheet1']
sheet2 = wb2['Details']
sheet4=wb2['PGOLD Death']
sheet3= wb3['Deceased Members']

In [3]:
rows=20000
columns = 66 

listab=[]
for i in range(1,rows+1):
    listab.append([])

    #copy sheet 
for r in range(1,rows+1):
    for c in range (1,columns+1):
        e=sheet.cell(row=r,column=c)
        listab[r-1].append(e.value)
    #paste sheet to sheet2 details
for r in range(1,rows+1):
    for c in range(1,columns+1):
        j=sheet2.cell(row=r+1,column=c)
        j.value=listab[r-1][c-1]

In [4]:
rows=2000
columns = 6 

listab=[]
for i in range(1,rows+1):
    listab.append([])
    #copy deceased memebers from dod
for r in range(1,rows+1):
    for c in range (1,columns+1):
        e=sheet3.cell(row=r,column=c)
        listab[r-1].append(e.value)
    #paste to pgold death sheet4 
for r in range(1,rows+1):
    for c in range(1,columns+1):
        j=sheet4.cell(row=r,column=c)
        j.value=listab[r-1][c-1]
sheet4.delete_rows(1)
sheet4.delete_rows(1)
sheet4.delete_cols(1)
Link=r'L:\ESI\PDP Weekly Reports\2024 Reports\2024 10 14 EGWP PDP report.xlsx'
wb2.save(Link)

In [5]:
import pandas as pd
PDP1 = pd.read_excel(r'L:\ESI\PDP Weekly Reports\2024 Reports\2024 10 07 EGWP PDP report.xlsx', sheet_name='Details')

In [6]:
import pandas as pd
PDP2 = pd.read_excel(Link, sheet_name='Details')

In [7]:
MAX_1 = PDP1.loc[:,'Op. Dte'].max()
print(MAX_1)

20241005

In [8]:
PDP2.loc[:,'Op. Dte'].max()

20241012

In [9]:
#Medicare A 
A=PDP2.loc[(PDP2['Op. Dte'] >MAX_1) & (PDP2['Status Code'] == 8) & (PDP2['TRR'] =='079') ]
A

C:\program files\AnacondaPython\lib\site-packages\pandas\core\ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

Empty DataFrame
Columns: [HIC, LT NME, FT NME, MI, Sex, DOB, PBP #, CMS Contract #, Dis. Reason, Eff. DTE, Creditable Cov Flag, # of Uncovered Months, Filler, Pov Level, Grp. #, SSN, TRR, TRR Txt, Dis Dte, Contract ID, carrier, Mem #, Status Code, New Sub., Change IND, Op. Dte, Reason Code, Current Group Effective Date, Filler1, Filler2, Date of Death, LICS_Copay_Cat1, LICS_Subsidy_Pct_1, LICS_Eff_Dte_1, LICS_End_dte_1, LICS_Copay_Cat_2, LICS_Subsidy_Pct_2, LICS_Eff_Dte_2, LICS_End_dte_2, LICS_Copay_Cat_3, LICS_Subsidy_Pct_3, LICS_Eff_Dte_3, LICS_End_dte_3, LICS_Copay_Cat_4, LICS_Subsidy_Pct_4, LICS_Eff_Dte_4, LICS_End_dte_4, LICS_Copay_Cat_5, LICS_Subsidy_Pct_5, LICS_Eff_Dte_5, LICS_End_dte_5, LEP_Eff_Dte_1, LEP_End_dte_1, LEP_Amt_1, LEP_Eff_Dte_2, LEP_End_dte_2, LEP_Amt_2, LEP_Eff_Dte_3, LEP_End_dte_3, LEP_Amt_3, Subscriber_Nbr, Previous HICN, Multiple EGWP Indicator, Participant ID 4, Dual Coverage Ind, Last Reject Desc]
Index: []

[0 rows x 66 columns]

In [10]:
#Medicare B
B=PDP2.loc[(PDP2['Op. Dte'] >MAX_1) & (PDP2['Status Code'] == 8) & (PDP2['TRR'] == '081') ]
B

Empty DataFrame
Columns: [HIC, LT NME, FT NME, MI, Sex, DOB, PBP #, CMS Contract #, Dis. Reason, Eff. DTE, Creditable Cov Flag, # of Uncovered Months, Filler, Pov Level, Grp. #, SSN, TRR, TRR Txt, Dis Dte, Contract ID, carrier, Mem #, Status Code, New Sub., Change IND, Op. Dte, Reason Code, Current Group Effective Date, Filler1, Filler2, Date of Death, LICS_Copay_Cat1, LICS_Subsidy_Pct_1, LICS_Eff_Dte_1, LICS_End_dte_1, LICS_Copay_Cat_2, LICS_Subsidy_Pct_2, LICS_Eff_Dte_2, LICS_End_dte_2, LICS_Copay_Cat_3, LICS_Subsidy_Pct_3, LICS_Eff_Dte_3, LICS_End_dte_3, LICS_Copay_Cat_4, LICS_Subsidy_Pct_4, LICS_Eff_Dte_4, LICS_End_dte_4, LICS_Copay_Cat_5, LICS_Subsidy_Pct_5, LICS_Eff_Dte_5, LICS_End_dte_5, LEP_Eff_Dte_1, LEP_End_dte_1, LEP_Amt_1, LEP_Eff_Dte_2, LEP_End_dte_2, LEP_Amt_2, LEP_Eff_Dte_3, LEP_End_dte_3, LEP_Amt_3, Subscriber_Nbr, Previous HICN, Multiple EGWP Indicator, Participant ID 4, Dual Coverage Ind, Last Reject Desc]
Index: []

[0 rows x 66 columns]

In [30]:
#Disenrollment 
O=PDP2.loc[(PDP2['Op. Dte'] >MAX_1) & (PDP2['Status Code'] == 16) & PDP2['Date of Death'].isnull() ]
O

,HIC,LT NME,FT NME,MI,Sex,DOB,PBP #,CMS Contract #,Dis. Reason,Eff. DTE,...,LEP_Amt_2,LEP_Eff_Dte_3,LEP_End_dte_3,LEP_Amt_3,Subscriber_Nbr,Previous HICN,Multiple EGWP Indicator,Participant ID 4,Dual Coverage Ind,Last Reject Desc
1390,1V10EK2YH46,PETTY,JOE,L,1,19360705,801,S5660,M08,20120101,...,NaN,NaN,NaN,NaN,427640569,NaN,NaN,NaN,NaN,NaN
5548,4H72CT6QX14,HIDALGO,EVA,NaN,2,19570522,801,S5660,NaN,20220501,...,NaN,NaN,NaN,NaN,334567747,NaN,NaN,NaN,NaN,NaN
6619,5AE4JW8MP63,OGILVIE,IRENE,B,2,19471220,801,S5660,M09,20180101,...,NaN,NaN,NaN,NaN,335423886,NaN,NaN,NaN,NaN,NaN
8458,6C85F93EN57,GOODMAN,RUTH,B,2,19330630,801,S5660,M09,20120101,...,NaN,NaN,NaN,NaN,179366431793,NaN,NaN,NaN,NaN,NaN
8909,6JK2QP1DY16,OLEARY,JOHN,J,1,19430730,801,S5660,M08,20120101,...,NaN,NaN,NaN,NaN,325366864,NaN,NaN,NaN,NaN,NaN
10202,7EC5UP3UE53,DIORI,ESTHER,M,2,19490822,801,S5660,M08,20140801,...,NaN,NaN,NaN,NaN,355440032,NaN,NaN,NaN,NaN,NaN
14008,9K29XK4HA11,FREEDMAN,RUTH,L,2,19281130,801,S5660,M08,20120101,...,NaN,NaN,NaN,NaN,335203050,NaN,NaN,NaN,NaN,NaN
14190,9N72M70ND08,JACKSON,JOYCE,M,2,19360405,801,S5660,M09,20120101,...,NaN,NaN,NaN,NaN,256544586,NaN,NaN,NaN,NaN,NaN

In [29]:
D=PDP2.loc[(PDP2['Op. Dte'] >MAX_1) & (PDP2['Status Code'] == 16) & (PDP2['Date of Death'] !='        ') & PDP2['Date of Death'].notnull() ]
D

,HIC,LT NME,FT NME,MI,Sex,DOB,PBP #,CMS Contract #,Dis. Reason,Eff. DTE,...,LEP_Amt_2,LEP_Eff_Dte_3,LEP_End_dte_3,LEP_Amt_3,Subscriber_Nbr,Previous HICN,Multiple EGWP Indicator,Participant ID 4,Dual Coverage Ind,Last Reject Desc
294,1EY0CA4FP00,DIXON,ANDRE,S,1,19470303,801,S5660,NaN,20120301,...,NaN,NaN,NaN,NaN,336401407,NaN,NaN,NaN,NaN,NaN
1319,1U17NK1EM59,SUSSMAN,EARL,D,1,19380322,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,349309898,NaN,NaN,NaN,NaN,NaN
2736,2Q80VX4DV03,DI PEGO,DOLORES,B,2,19290729,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,352223638,NaN,NaN,NaN,NaN,NaN
3028,2VQ3HF2JF85,BUTLER,SHIRLEY,J,2,19460314,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,430767162,NaN,NaN,NaN,NaN,NaN
5005,4AT1FK5XM31,SWAIN,JOAN,B,2,19310720,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,360243418,NaN,NaN,NaN,NaN,NaN
5625,4KD3N71AT85,LAMBERT,BARBARA,J,2,19410812,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,426928653,NaN,NaN,NaN,NaN,NaN
5867,4PE9JM3VF36,GAULKE,MARY,J,2,19280704,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,346201961,NaN,NaN,NaN,NaN,NaN
5910,4PU8XX6QT20,ACHUSIM,BETTYE,H,2,19450522,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,427841822,NaN,NaN,NaN,NaN,NaN
6803,5DM0VQ7PN47,PETERSON,ELEANOR,A,2,19331104,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,330289977,NaN,NaN,NaN,NaN,NaN
6834,5DW9AV6EF49,GRANT,BEVERLY,A,2,19490622,801,S5660,NaN,20140701,...,NaN,NaN,NaN,NaN,353404597,NaN,NaN,NaN,NaN,NaN
6876,5EG3FK7TK11,FALK,VIVIEN,L,2,19370327,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,335305353,NaN,NaN,NaN,NaN,NaN
7004,5F49FQ8CX11,KLEIN,LYNETTE,A,2,19440504,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,348369816,NaN,NaN,NaN,NaN,NaN
8352,6A09WT8PG24,GARCIA FERRE,VIVIAN,I,2,19361105,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,339583296,NaN,NaN,NaN,NaN,NaN
8932,6JU5RH9XT60,WILSON,JOHNNY,N,2,19370803,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,324329328,NaN,NaN,NaN,NaN,NaN
8993,6KQ7UP0VN71,MARKOU,JOAN,B,2,19310329,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,339248323,NaN,NaN,NaN,NaN,NaN
9998,7AU2AN3CN14,SIMMONS,DONOVAN,NaN,1,19460623,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,350381241,NaN,NaN,NaN,NaN,NaN
10509,7JG0QC9YY23,MULVIHILL,THERESE,B,2,19280311,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,360200732,NaN,NaN,NaN,NaN,NaN
11382,7W66UN6YQ47,BARLOW,OUIDA,NaN,2,19350528,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,252647422,NaN,NaN,NaN,NaN,NaN
12067,8G20EU4CP22,BARBER,BLANCHE,M,2,19370113,801,S5660,NaN,20140101,...,NaN,NaN,NaN,NaN,324306463,NaN,NaN,NaN,NaN,NaN
12334,8K03AW9HY70,SNIEZEK,JAMEY,S,2,19400321,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,351309507,351309507A,NaN,NaN,NaN,NaN
13341,9CD0U36FK48,GOLDBERG,ROBERT,NaN,1,19320306,801,S5660,NaN,20120101,...,NaN,NaN,NaN,NaN,330241786,NaN,NaN,NaN,NaN,NaN

In [13]:
import openpyxl 
from openpyxl import load_workbook

wb2=openpyxl.load_workbook(r'C:\Users\kwokj\Downloads\test.xlsx')

wb2['Sheet1'].delete_rows(1, sheet.max_row)

sheet2 = wb2['Sheet1']



wb2.save(r'C:\Users\kwokj\Downloads\test.xlsx')

In [14]:
Medicare_A = pd.read_excel(r'C:\Users\kwokj\Downloads\test.xlsx', sheet_name='Sheet1')

filtered_data =PDP2.loc[(PDP2['Op. Dte'] >MAX_1) & (PDP2['Status Code'] == 8) & (PDP2['TRR'] =='079') ]


combined_data=pd.concat([Medicare_A,filtered_data])
combined_data.to_excel(r'C:\Users\kwokj\Downloads\test.xlsx', sheet_name='Sheet1', index=False)

In [15]:
import openpyxl 
from openpyxl import load_workbook
wb=openpyxl.load_workbook(Link)
wb2=openpyxl.load_workbook(r'C:\Users\kwokj\Downloads\test.xlsx')


sheet= wb['A']
sheet2 = wb2['Sheet1']



rows=50
columns = 66 

listab=[]
for i in range(1,rows+1):
    listab.append([])
    #copy a
for r in range(1,rows+1):
    for c in range (1,columns+1):
        e=sheet2.cell(row=r,column=c)
        listab[r-1].append(e.value)
    #paste to a
for r in range(1,rows+1):
    for c in range(1,columns+1):
        j=sheet.cell(row=r,column=c)
        j.value=listab[r-1][c-1]


wb.save(Link)
wb2['Sheet1'].delete_rows(1, sheet.max_row)

In [16]:
Medicare_B = pd.read_excel(r'C:\Users\kwokj\Downloads\test.xlsx', sheet_name='Sheet1')

filtered_data =PDP2.loc[(PDP2['Op. Dte'] >MAX_1) & (PDP2['Status Code'] == 8) & (PDP2['TRR'] == '081') ]


combined_data=pd.concat([Medicare_A,filtered_data])
combined_data.to_excel(r'C:\Users\kwokj\Downloads\test.xlsx', sheet_name='Sheet1', index=False)

In [17]:
import openpyxl 
from openpyxl import load_workbook
wb=openpyxl.load_workbook(Link)
wb2=openpyxl.load_workbook(r'C:\Users\kwokj\Downloads\test.xlsx')

sheet= wb['B']
sheet2 = wb2['Sheet1']

rows=50
columns = 66 

listab=[]
for i in range(1,rows+1):
    listab.append([])
    #copy b
for r in range(1,rows+1):
    for c in range (1,columns+1):
        e=sheet2.cell(row=r,column=c)
        listab[r-1].append(e.value)
    #paste b 
for r in range(1,rows+1):
    for c in range(1,columns+1):
        j=sheet.cell(row=r,column=c)
        j.value=listab[r-1][c-1]


wb.save(Link)
wb2['Sheet1'].delete_rows(1, sheet.max_row)

In [18]:
Medicare_O = pd.read_excel(r'C:\Users\kwokj\Downloads\test.xlsx', sheet_name='Sheet1')

filtered_data =PDP2.loc[(PDP2['Op. Dte'] >MAX_1) & (PDP2['Status Code'] == 16) & (PDP2['Date of Death'] =='        ') ]


combined_data=pd.concat([Medicare_A,filtered_data])
combined_data.to_excel(r'C:\Users\kwokj\Downloads\test.xlsx', sheet_name='Sheet1', index=False)

In [19]:
import openpyxl 
from openpyxl import load_workbook
wb=openpyxl.load_workbook(Link)
wb2=openpyxl.load_workbook(r'C:\Users\kwokj\Downloads\test.xlsx')


sheet= wb['O']
sheet2 = wb2['Sheet1']

rows=50
columns = 66 

listab=[]
for i in range(1,rows+1):
    listab.append([])
    #copy o
for r in range(1,rows+1):
    for c in range (1,columns+1):
        e=sheet2.cell(row=r,column=c)
        listab[r-1].append(e.value)
    #paste o
for r in range(1,rows+1):
    for c in range(1,columns+1):
        j=sheet.cell(row=r,column=c)
        j.value=listab[r-1][c-1]


wb.save(Link)
wb2['Sheet1'].delete_rows(1, sheet.max_row)

In [20]:
Medicare_D = pd.read_excel(r'C:\Users\kwokj\Downloads\test.xlsx', sheet_name='Sheet1')

filtered_data =PDP2.loc[(PDP2['Op. Dte'] >MAX_1) & (PDP2['Status Code'] == 16) & (PDP2['Date of Death'] !='        ') ]


combined_data=pd.concat([Medicare_A,filtered_data])
combined_data.to_excel(r'C:\Users\kwokj\Downloads\test.xlsx', sheet_name='Sheet1', index=False)

In [21]:
import openpyxl 
from openpyxl import load_workbook
wb=openpyxl.load_workbook(Link)
wb2=openpyxl.load_workbook(r'C:\Users\kwokj\Downloads\test.xlsx')


sheet= wb['PDP Death']
sheet2 = wb2['Sheet1']

rows=50
columns = 66 

listab=[]
for i in range(1,rows+1):
    listab.append([])
    #copy d
for r in range(1,rows+1):
    for c in range (1,columns+1):
        e=sheet2.cell(row=r,column=c)
        listab[r-1].append(e.value)
    #paste d
for r in range(1,rows+1):
    for c in range(1,columns+1):
        j=sheet.cell(row=r,column=c)
        j.value=listab[r-1][c-1]
        
        
sheet.delete_cols(32,66)
sheet.delete_cols(1,15)
sheet['Q2'] ="=VLOOKUP(A2,'PGOLD Death'!$A$2:$D$1000,4,FALSE)"

wb.save(Link)
wb2['Sheet1'].delete_rows(1, sheet.max_row)

In [22]:
# import openpyxl 
# from openpyxl import load_workbook

# wb2=openpyxl.load_workbook(r'C:\Users\JamesK\Downloads\test.xlsx')

# wb2['Sheet1'].delete_rows(1, sheet.max_row)

# sheet2 = wb2['Sheet1']



# wb2.save(r'C:\Users\JamesK\Downloads\test.xlsx')

In [23]:
# import openpyxl 
# from openpyxl import load_workbook
# wb=openpyxl.load_workbook(r'L:\ESI\PDP Weekly Reports\2023 Reports\2023 11 07 EGWP PDP report.xlsx')



# sheet= wb['PDP Death']

# sheet.delete_cols(32,66)
# sheet.delete_cols(1,15)

# wb.save(r'L:\ESI\PDP Weekly Reports\2023 Reports\2023 11 07 EGWP PDP report.xlsx')